### ISSUE TITLE
Get ghi to run on ubuntu for win10

### ISSUE THREAD

**Issue by lakruzz** [prolike/prolike-stack#5]
We sometimes use the [GHI](https://github.com/stephencelis/ghi) features too

related to #1

**Comment by LouBNielsen** [comment]
First of all, install rubygems for Ubunto: https://stackoverflow.com/questions/5736568/can-i-install-gems-with-apt-get-on-ubuntu

I did that because I got this error when trying to run 'ghi' 
![image](https://user-images.githubusercontent.com/17924001/40644327-27415e6e-6323-11e8-909b-4a1faddace28.png)

**Comment by LouBNielsen** [comment]
When rybygems and ghi is installed, your authorazation are required
![image](https://user-images.githubusercontent.com/17924001/40644493-b4f65598-6323-11e8-80c0-23f81f304ab8.png)

Setup ghi with your github user

Then you are able to see git issues that are assigned to you:

![image](https://user-images.githubusercontent.com/17924001/40644551-d9d348bc-6323-11e8-996c-7736d1d4c580.png)
